# frozen_string_literal: true

module Propshaft::Resolver
  class Static
    attr_reader :manifest_path, :prefix

    def initialize(manifest_path:, prefix:)
      @manifest_path = manifest_path
      @prefix = prefix
      @manifest = Propshaft::Manifest.from_path(manifest_path)
      @logical_paths_by_content_type = @manifest.logical_paths_by_content_type
      @app_logical_paths_by_content_type = @manifest.logical_paths_by_content_type(app: true)
      @knows_app_assets = @manifest.knows_app_assets?
    end

    def resolve(logical_path)
      if asset_path = digested_path(logical_path)
        File.join prefix, asset_path
      end
    end

    def integrity(logical_path)
      entry = @manifest[logical_path]

      entry&.integrity
    end

    def read(logical_path, encoding: "ASCII-8BIT")
      if asset_path = digested_path(logical_path)
        File.read(manifest_path.dirname.join(asset_path), encoding: encoding)
      end
    end

    def asset_paths_by_type(extension)
      @logical_paths_by_content_type[Mime::Type.lookup_by_extension(extension)] || []
    end

    def app_asset_paths_by_type(extension)
      if @knows_app_assets
        @app_logical_paths_by_content_type[Mime::Type.lookup_by_extension(extension)] || []
      else
        warn_about_outdated_manifest
        nil
      end
    end

    private
      def warn_about_outdated_manifest
        return if @warned_about_outdated_manifest

        Propshaft.logger.warn <<~MESSAGE
          The manifest at '#{manifest_path}' was generated by an older version of Propshaft,
          so app assets are being looked up on disk.
          Run bin/rails assets:precompile to regenerate it.
        MESSAGE

        @warned_about_outdated_manifest = true
      end

      def digested_path(logical_path)
        entry = @manifest[logical_path]

        entry&.digested_path
      end
  end
end
