# frozen_string_literal: true

require "test_helper"
require "minitest/mock"
require "propshaft/resolver/static"

module Propshaft::Resolver::StaticTests
  extend ActiveSupport::Concern

  included do
    test "resolving present asset returns uri path" do
      assert_equal \
        "/assets/one-f2e1ec14.txt",
        resolver.resolve("one.txt")
    end

    test "reading static asset" do
      assert_equal "ASCII-8BIT", resolver.read("one.txt").encoding.to_s
      assert_equal "One from first path", resolver.read("one.txt")
    end

    test "reading static asset with encoding option" do
      assert_equal "UTF-8", resolver.read("one.txt", encoding: "UTF-8").encoding.to_s
      assert_equal "One from first path", resolver.read("one.txt", encoding: "UTF-8")
    end

    test "resolving missing asset returns nil" do
      assert_nil resolver.resolve("nowhere.txt")
    end

    test "asset paths by type returns empty array when no asset matches" do
      assert_equal [], resolver.asset_paths_by_type("png")
    end

    test "integrity for missing asset returns nil" do
      assert_nil resolver.integrity("nowhere.txt")
    end

    test "resolver requests json optimizer gems to keep parsed manifest keys as strings" do
      called = false

      stub = Proc.new do |_, opts|
        assert_equal false, opts[:symbolize_names]
        called = true
        {}
      end

      JSON.stub :parse, stub do
        resolver.resolve("one.txt")
      end

      assert called
    end
  end
end

class Propshaft::Resolver::StaticTest < ActiveSupport::TestCase
  include Propshaft::Resolver::StaticTests

  test "asset paths by type returns the paths for the extension's content type" do
    assert_equal [ "hello_world.css", "styles/print.css" ], resolver.asset_paths_by_type("css")
    assert_equal [ "hello_world.js" ], resolver.asset_paths_by_type("js")
  end

  test "integrity for asset returns nil for simple manifest" do
    assert_nil resolver.integrity("one.txt")
  end

  test "app asset paths by type returns nil and warns once for a manifest without app assets recorded" do
    logger, Propshaft.logger = Propshaft.logger, Logger.new(output = StringIO.new)

    assert_nil resolver.app_asset_paths_by_type("css")
    assert_nil resolver.app_asset_paths_by_type("js")

    assert_equal 1, output.string.scan("was generated by an older version of Propshaft").count
  ensure
    Propshaft.logger = logger
  end

  private
    def resolver
      @resolver ||= Propshaft::Resolver::Static.new(
        manifest_path: Pathname.new("#{__dir__}/../../fixtures/output/.manifest.json"),
        prefix: "/assets"
      )
    end
end

class Propshaft::Resolver::StaticTest::WithExtensibleManifest < ActiveSupport::TestCase
  include Propshaft::Resolver::StaticTests

  test "integrity for asset returns value from extensible manifest" do
    assert_equal "sha384-LdS8l2QTAF8bD8WPb8QSQv0skTWHhmcnS2XU5LBkVQneGzqIqnDRskQtJvi7ADMe", resolver.integrity("one.txt")
  end

  test "app asset paths by type only returns paths for app assets" do
    assert_equal [ "another.css", "hello_world.css" ], resolver.asset_paths_by_type("css")
    assert_equal [ "hello_world.css" ], resolver.app_asset_paths_by_type("css")
  end

  private
    def resolver
      @resolver ||= Propshaft::Resolver::Static.new(
        manifest_path: Pathname.new("#{__dir__}/../../fixtures/new_manifest_format/.manifest.json"),
        prefix: "/assets"
      )
    end
end
