name: CI
on: [push, pull_request]
jobs:
  tests:
    strategy:
      matrix:
        ruby-version:
          - "2.7"
          - "3.0"
          - "3.1"
        continue-on-error: [false]

    name: ${{ format('Tests (Ruby {0})', matrix.ruby-version) }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.continue-on-error }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: bin/test
